#! /bin/bash

if [ $# -eq 0 ]; then

    gen_cols

    tau=`awk '/#C# τC/ {print $4}' output-data | sed "s/,//"`
    output_file=`printf "data_ext_t%08.03f" $tau`

    # print all columns (vrms, thruput, etc)
    awk '/#ext#/ {$1=""; print} ' output-data > $output_file && xmgrace -free -noask -nxy $output_file

else
    echo "Given $? args, need either:" >&2
    echo " * 0 args (prints all quantities)" >&2
    exit -1
fi

